LoadModule wsgi_module "/opt/uv/mod_wsgi/current/mod_wsgi.so"

RewriteEngine on
RewriteCond %{REQUEST_URI} !^/robots.txt
RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [L,R]
LogLevel info
AliasMatch ^/([^/]*\.css) /data/deft/python3/panda-bigmon-atlas/atlas/static_media/$1
Alias /static/ /data/deft/python3/panda-bigmon-atlas/atlas/static_media/

<Directory /data/deft/python3/panda-bigmon-atlas/atlas/static_media>
Require all granted
</Directory>


WSGISocketPrefix run/wsgi.prodtask.atlas
WSGIProcessGroup bigpandamon-atlas
WSGIApplicationGroup %{GLOBAL}
WSGIDaemonProcess bigpandamon-atlas processes=1 threads=5 python-home=/opt/uv/venv memory-limit=5000000000


WSGIPassAuthorization On
WSGIScriptAlias / /data/deft/python3/panda-bigmon-atlas/atlas/wsgi.py process-group=bigpandamon-atlas

<Directory /data/deft/python3/panda-bigmon-atlas/atlas/>
    <Files wsgi.py>
            Require all granted
    </Files>
</Directory>
<Location "/">
    Order allow,deny
    Allow from all
    WSGIProcessGroup bigpandamon-atlas
 </Location>

LogLevel info
ErrorLog  logs/prodmon.web-error_log
TransferLog logs/prodmon.web-access_log

### for Computer.Security @ CERN
RewriteEngine on
RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
RewriteRule .* - [F]